name: test_confetti
description: A new Flutter project.

version: 1.0.0+1

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  confetti:
    path: ../flutter_confetti
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true